[package]
name = "rice-wgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
rice-layout = { path = "../rice-layout", features = ["pod"] }
wgpu = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
env_logger = { workspace = true }
bytemuck = { workspace = true }
