[package]
name = "rice-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
rice-dom = { path = "../rice-dom" }
rice-layout = { path = "../rice-layout" }
rice-parser = { path = "../rice-parser" }
rice-wgpu = { path = "../rice-wgpu" }
